services:
  backend-api:
    image: ${DOCKER_USERNAME}/${PROJECT_NAME}:latest
    container_name: stocky-ai-fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - stocky-net
    restart: always # 컨테이너 종료시 자동 재시작

  retrieval-worker:
    image: ${DOCKER_USERNAME}/${PROJECT_NAME}:latest #같은 이미지 사용
    container_name: stocky-ai-worker
    command: python -m app.sqs.worker.main_worker #백그라운드 sqs 감지용 작동
    env_file:
      - .env
    networks:
      - stocky-net
    depends_on:
      - backend-api
    restart: always # 컨테이너 종료시 자동 재시작

networks:
  stocky-net:
    external: true