name: FastAPI CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ] # develop, main 브랜치 감시

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=develop,enable=${{ github.ref == 'refs/heads/develop' }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 위에서 만든 태그 적용
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    needs: build-and-push
    if: github.ref == 'refs/heads/main' # main 브랜치일 때만 실행
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/apps/fastapi-ai

      - name: Copy Docker Compose file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key:  ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.deploy.yml"
          target: "/home/ubuntu/apps/fastapi-ai"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/apps/fastapi-ai
            
            # .env 파일 생성
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
            echo "PROJECT_NAME=${{ secrets.PROJECT_NAME }}" >> .env
            echo "${{ secrets.ENV_VARS }}" >> .env
            
            mv docker-compose.deploy.yml docker-compose.yml
            
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker-compose pull
            sudo docker-compose up -d --remove-orphans
            sudo docker image prune -f